### PR TITLE
Improve style of tables on large screens

### PR DESCRIPTION
**Pull request by adrienluitot**
- Darkened .row-even
- Increased the padding of the rows
- Removed the margin from rows in nodes.html
- Added top-margin to the rows heads

### CODE REVIEW

**Comment by adrienluitot** [comment]
According to this issue #27 
Here some pictures : 
image

Night mode:
image

**Comment by AdamHebby** [comment]
I've also been working on this and whilst I haven't gotten as far as you, I was going for the same kind of thing. Increasing padding of rows and breaking up the groups a bit more.

I gotta say though, your screenshots look better than what I was going for, but who knows what mine might have snowballed into.

My one gripe is your line heights / vertical centering seem to be a bit off, screenshot:
image

I'm talking about the text in the pills, and the pills not being in line with the text. Obvs not my repo / decision but thought I'd offer my two cents.

**Comment by adrienluitot** [comment]
You're right, I didn't catch it :D 
I wanted to align vertically everythting in the middle, but seems that Bootstrap 3 and classical divs doesn't like that x)

**Comment by nook24** [comment]
Many thanks @adrienluitot. This looks much cleaner and structurized, i appreciate this! 

~~It looks like the labels in the menu got some unwanted padding.~~ _I guess this was always an issue, I'm not sure_

Also as @AdamHebby mentioned the service name and the status pills are not on the same hight.

Bildschirmfoto 2019-10-05 um 13 39 12

Would be great if you could take a look at this.

**Comment by adrienluitot** [comment]
I'll try to fix it ;)

**Comment by adrienluitot** [comment]
Hmm it's seem to be due to the font :/

**Comment by nook24** [comment]
Thanks!
I will also take a look at this tomorrow :)

**Comment by adrienluitot** [comment]
I'm doing some checks, seems that even with an other font the problem isn't fully fixed.

**Comment by adrienluitot** [comment]
It seems to fix the bug, it's not perfect at all, but it does the trick.

**Comment by nook24** [comment]
Sorry for my late response on this. That's definitely much better than my original, many thanks!

**Pull request merged**
